Repository hackathon-equipe/HackathonFrontEnd, pull requests merged in 2024-11, with the labels that each got.

#40 FEAT: Adicionando paginação sem api #34
  package-lock.json
  package.json
  src/assets/images/arrow-gray.png
  src/assets/images/arrow-right.png
  src/components/paginacao/DefaultPaginacao.vue
  src/components/paginacao/PaginacaoVue.vue
  src/components/produtos/PadraoProdutos.vue
  src/views/ProdutosView.vue
Labels: enhancement

#42 Criado página do sobre e correção da animação das propagandas
  src/components/header/caminho/PadraoCaminho.vue
  src/components/header/propagandas/PadraoPropagandas.vue
  src/components/icons/blackFacebookIcon.vue
  src/components/icons/blackInstagramIcon.vue
  src/components/icons/index.js
  src/components/icons/twitterIcon.vue
  src/components/icons/whiteEmailIcon.vue
  src/components/icons/whiteMarkIcon.vue
  src/components/icons/whitePhoneIcon.vue
  src/components/sobrenos/sobrenosImgComp.vue
  src/views/SobreView.vue
Labels: bug, enhancement

#44 Feat 39
  src/components/filtros/AsideFiltro.vue
  src/components/filtros/InputPreco.vue
  src/components/filtros/ItensSelect.vue
  src/stores/categoriaFiltros.js
Labels: enhancement

#45 FEAT: Criadas rotas dos produtos de modo funcional #16
  src/components/header/ProdutosHeader.vue
  src/components/navbar/PadraoNavegacao.vue
  src/components/produtos/ListaProdutos.vue
  src/router/index.js
  src/stores/categoriaFiltros.js
  src/stores/filtros.js
  src/stores/produtosStore.js
  src/stores/rotas.js
Labels: enhancement

#49 Fix 48
  src/assets/base.css
  src/assets/images/estrelas1.png
  src/assets/images/image-removebg-preview (3).png
  src/assets/images/placa555.png
  src/assets/images/placa590.png
  src/assets/images/placa630.png
  src/assets/images/placa630kit4un.png
  src/assets/images/placaskit2un.png
  src/components/carousel/PadraoCarousel.vue
  src/components/carousel/SlideComponent.vue
  src/components/filtros/AsideFiltro.vue
  src/components/filtros/InputPreco.vue
  src/components/filtros/ItensSelect.vue
  src/components/filtros/OrdenarFiltro.vue
  src/components/header/caminho/PadraoCaminho.vue
  src/components/homeComponents/sugestIcons.vue
  src/components/navbar/PadraoNavegacao.vue
  src/components/navbar/titulos/ListaTitulos.vue
  src/components/produtos/PadraoProdutos.vue
  src/router/index.js
  src/stores/categoriaFiltros.js
  src/stores/produtosStore.js
  src/views/HomeView.vue
Labels: bug

#50 FEAT: Interligar backend user
  package-lock.json
  package.json
  src/api/usuario.js
  src/assets/images/usersemfoto.jpg
  src/components/homeComponents/beneficiesCards.vue
  src/components/navbar/PadraoNavegacao.vue
  src/composables/auth.js
  src/main.js
  src/plugins/axios.js
  src/router/index.js
  src/service/auth.js
  src/stores/auth.js
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/perfilView.vue
Labels: enhancement

#43 adicionado gif ao nao conter itens no carrinho, refeita pagina de carrinho
  src/assets/images/LoadGif/LoadingAnimation.gif
  src/assets/images/LoadGif/check-mark-verified.gif
  src/assets/images/OrcamentoGif/OrcamentoGIf.gif
  src/components/grafico/OrcamentoGrafico.vue
  src/components/icons/index.js
  src/components/icons/upArrowIcon.vue
  src/components/navbar/PadraoNavegacao.vue
  src/components/produtos/informacoes/InformacoesProduto.vue
  src/router/index.js
  src/stores/carrinhoStore.js
  src/stores/cursto-irradiacaoStore.js
  src/stores/orcamentoStore.js
  src/stores/pagamentoStore.js
  src/views/CarrinhoView.vue
  src/views/OrcamentosView.vue
  src/views/SobreView.vue
  src/views/pagamentoView.vue
Labels: enhancement

#54 FEAT: instalendo chart.js #53
  package-lock.json
  package.json
Labels: enhancement

#55 FEAT: Carregamento
  src/components/navbar/PadraoNavegacao.vue
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/perfilView.vue
Labels: enhancement

#56 feat: animacoes basicas feitas #52
  src/assets/images/bunnerHome/bunnerHomePage.vue
  src/components/footer/Navegação/LinksFooter.vue
  src/components/homeComponents/beneficiesCards.vue
  src/components/homeComponents/contactComp.vue
  src/components/navbar/PadraoNavegacao.vue
  src/components/produtos/PadraoProdutos.vue
  src/components/produtos/informacoes/InformacoesProduto.vue
  src/stores/produtosStore.js
  src/views/HomeView.vue
  src/views/SobreView.vue
Labels: enhancement

#57 fix: alterado valor do orçamento e corrigido botão duplicado #52
  src/components/navbar/PadraoNavegacao.vue
  src/stores/orcamentoStore.js
Labels: documentation

#58 fix: corrigido distancia do titulo na pagina sobre e alterado cor dos…
  src/assets/base.css
  src/views/SobreView.vue
Labels: enhancement

#59 fix: corrigido distancia do titulo na pagina sobre e alterado cor dos…
  src/assets/base.css
  src/assets/images/bunnerHome/bunnerHomePage.vue
  src/components/navbar/PadraoNavegacao.vue
  src/components/produtos/informacoes/InformacoesProduto.vue
  src/stores/rotas.js
Labels: enhancement

#62 Refactor 60
  src/components/carrinho/componentes/index.js
  src/components/carrinho/componentes/inputAplicarComp.vue
  src/components/carrinho/componentes/itemCarrinho.vue
  src/components/carrinho/componentes/itensNoCarrinho.vue
  src/components/carrinho/componentes/notificacaoAdicionarItem.vue
  src/components/carrinho/componentes/notificacaoRemovidoCarrinho.vue
  src/components/carrinho/componentes/resumoCarrinho.vue
  src/components/carrinho/componentes/semItensNoCarrinho.vue
  src/components/carrinho/itemCarrinho.vue
  src/components/carrinho/padraoCarrinho.vue
  src/components/produtos/informacoes/InformacoesProduto.vue
  src/stores/carrinhoStore.js
  src/stores/orcamentoStore.js
  src/views/CarrinhoView.vue
  src/views/SobreView.vue
Labels: enhancement

#66 Feat 61: Fazendo comentarios e estrelas
  src/components/carousel/PadraoCarousel.vue
  src/components/carousel/SlideComponent.vue
  src/components/produtos/PadraoProdutos.vue
  src/components/produtos/ProdutoComponent.vue
  src/components/produtos/comentarios/AddComentario.vue
  src/components/produtos/comentarios/ComentarioProduto.vue
  src/components/produtos/informacoes/InformacoesProduto.vue
  src/stores/comentarios.js
  src/stores/produtosStore.js
  src/views/ProdutoView.vue
Labels: enhancement

#70 FEAT: Adaptando para backend #69
  index.html
  package-lock.json
  src/components/carousel/PadraoCarousel.vue
  src/components/carousel/SlideComponent.vue
  src/components/produtos/PadraoProdutos.vue
  src/components/produtos/ProdutoComponent.vue
  src/components/produtos/informacoes/InformacoesProduto.vue
  src/stores/categoriaFiltros.js
  src/stores/filtros.js
  src/stores/produtosStore.js
  src/views/ProdutoView.vue
Labels: enhancement

#68 Incluir backend no form de contato
  package-lock.json
  package.json
  src/plugins/axios.js
  src/views/SobreView.vue
Labels: enhancement

#73 Criar chamada de api produtos
  src/api/usuario.js
  src/service/avaliacoes.js
  src/service/compras.js
  src/service/cupons.js
  src/service/despesas.js
  src/service/enderecos.js
  src/service/fabricantes.js
  src/service/movimentacaoFinanceira.js
  src/service/orcamentos.js
  src/service/produtos.js
  src/service/telefones.js
  src/stores/filtros.js
  src/stores/produtosStore.js
Labels: enhancement

#76 Fazer conexao produto backend
  src/components/carousel/SlideComponent.vue
  src/components/produtos/ProdutoComponent.vue
  src/components/produtos/imagens/ImagemProduto.vue
  src/components/produtos/imagens/ImagensPqn.vue
  src/views/ProdutoView.vue
Labels: enhancement
